-- Open the Supabase Dashboard
-- Go to the "SQL Editor" on the left menu
-- Paste this script and click "Run"

CREATE TABLE extracted_links (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  url TEXT NOT NULL,
  tag TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
