"""
PDF writer — converts Markdown notes to professionally styled PDFs.

Uses Markdown → HTML → PDF pipeline with WeasyPrint and custom CSS.
Falls back to a basic HTML renderer if WeasyPrint is not available.
"""

from __future__ import annotations

from pathlib import Path
from typing import Optional

import markdown
from jinja2 import Template

from notes_ai.core.config import AppConfig
from notes_ai.utils.helpers import ensure_dir
from notes_ai.utils.logging import get_logger

logger = get_logger("export.pdf_writer")

# ---------------------------------------------------------------------------
# HTML Template
# ---------------------------------------------------------------------------

HTML_TEMPLATE = Template("""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <style>
        {{ css }}
    </style>
</head>
<body>
    <div class="document">
        <header>
            <h1 class="doc-title">{{ title }}</h1>
            <p class="doc-subtitle">AI-Generated Study Notes</p>
        </header>
        <main>
            {{ content }}
        </main>
        <footer>
            <p>Generated by notes-ai — AI-Powered Udemy Course Note Generator</p>
        </footer>
    </div>
</body>
</html>""")


class PDFWriter:
    """Converts Markdown notes to professionally styled PDF documents."""

    def __init__(self, config: AppConfig) -> None:
        self.config = config
        self.export_cfg = config.export

    def convert_markdown_to_pdf(
        self,
        markdown_path: Path,
        pdf_path: Path,
        title: str = "Study Notes",
    ) -> Path | None:
        """
        Convert a Markdown file to a PDF.

        Args:
            markdown_path: Path to the source Markdown file.
            pdf_path: Path to save the output PDF.
            title: Document title for the PDF header.

        Returns:
            Path to the generated PDF, or None on failure.
        """
        try:
            ensure_dir(pdf_path.parent)

            # Read markdown content
            md_content = markdown_path.read_text(encoding="utf-8")

            # Convert Markdown to HTML
            html_content = self._markdown_to_html(md_content)

            # Load CSS theme
            css = self._load_css()

            # Render full HTML document
            full_html = HTML_TEMPLATE.render(
                title=title,
                css=css,
                content=html_content,
            )

            # Convert HTML to PDF using WeasyPrint
            return self._html_to_pdf(full_html, pdf_path)

        except Exception as e:
            logger.error("PDF conversion failed: %s", e)
            return None

    def convert_all(
        self,
        output_dir: Path,
        title: str = "Study Notes",
    ) -> list[Path]:
        """
        Convert all Markdown files in a directory to PDF.

        Args:
            output_dir: Directory containing .md files.
            title: Base title for PDFs.

        Returns:
            List of paths to generated PDFs.
        """
        pdfs: list[Path] = []

        for md_file in sorted(output_dir.glob("*.md")):
            pdf_path = md_file.with_suffix(".pdf")
            result = self.convert_markdown_to_pdf(md_file, pdf_path, title=title)
            if result:
                pdfs.append(result)

        logger.info("Converted %d Markdown files to PDF", len(pdfs))
        return pdfs

    def _markdown_to_html(self, md_content: str) -> str:
        """
        Convert Markdown text to HTML with extensions.

        Supports code highlighting, tables, TOC, and more.
        """
        extensions = [
            "markdown.extensions.fenced_code",
            "markdown.extensions.codehilite",
            "markdown.extensions.tables",
            "markdown.extensions.toc",
            "markdown.extensions.nl2br",
            "markdown.extensions.sane_lists",
            "markdown.extensions.smarty",
        ]

        extension_configs = {
            "markdown.extensions.codehilite": {
                "css_class": "highlight",
                "linenums": False,
                "guess_lang": True,
            },
            "markdown.extensions.toc": {
                "permalink": False,
            },
        }

        return markdown.markdown(
            md_content,
            extensions=extensions,
            extension_configs=extension_configs,
        )

    def _load_css(self) -> str:
        """Load the CSS theme for PDF styling."""
        # Try to load custom CSS from templates directory
        templates_dir = Path(__file__).parent / "templates"
        css_path = templates_dir / "notes.css"

        if css_path.exists():
            return css_path.read_text(encoding="utf-8")

        # Fallback: embedded default CSS
        return self._default_css()

    def _html_to_pdf(self, html: str, pdf_path: Path) -> Path | None:
        """Convert HTML string to PDF using WeasyPrint."""
        try:
            from weasyprint import HTML

            HTML(string=html).write_pdf(str(pdf_path))
            size_mb = pdf_path.stat().st_size / 1e6
            logger.info("PDF generated: %s (%.1f MB)", pdf_path.name, size_mb)
            return pdf_path

        except ImportError:
            logger.warning(
                "WeasyPrint not installed. Install it for PDF export: "
                "pip install weasyprint"
            )
            # Save as HTML fallback
            html_path = pdf_path.with_suffix(".html")
            html_path.write_text(html, encoding="utf-8")
            logger.info("Saved as HTML fallback: %s", html_path)
            return None

        except Exception as e:
            logger.error("WeasyPrint PDF generation failed: %s", e)
            return None

    @staticmethod
    def _default_css() -> str:
        """Fallback embedded CSS if template file is not found."""
        return """
            @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&family=JetBrains+Mono:wght@400;500&display=swap');

            :root {
                --primary: #2563eb;
                --primary-light: #dbeafe;
                --text: #1e293b;
                --text-muted: #64748b;
                --bg: #ffffff;
                --border: #e2e8f0;
                --code-bg: #1e1e2e;
                --code-text: #cdd6f4;
                --success: #16a34a;
                --warning: #d97706;
                --danger: #dc2626;
            }

            * { box-sizing: border-box; margin: 0; padding: 0; }

            body {
                font-family: 'Inter', -apple-system, sans-serif;
                font-size: 11pt;
                line-height: 1.7;
                color: var(--text);
                background: var(--bg);
            }

            .document { max-width: 800px; margin: 0 auto; padding: 40px 50px; }

            header {
                text-align: center;
                margin-bottom: 40px;
                padding-bottom: 20px;
                border-bottom: 3px solid var(--primary);
            }

            .doc-title {
                font-size: 24pt;
                font-weight: 700;
                color: var(--primary);
                margin-bottom: 8px;
            }

            .doc-subtitle {
                font-size: 11pt;
                color: var(--text-muted);
                font-style: italic;
            }

            h1 { font-size: 20pt; color: var(--primary); margin: 30px 0 15px; font-weight: 700; }
            h2 { font-size: 16pt; color: var(--text); margin: 25px 0 12px; font-weight: 600; border-bottom: 2px solid var(--border); padding-bottom: 6px; }
            h3 { font-size: 13pt; color: var(--text); margin: 20px 0 10px; font-weight: 600; }
            h4 { font-size: 11pt; color: var(--text-muted); margin: 15px 0 8px; font-weight: 500; }

            p { margin: 8px 0; }

            ul, ol { margin: 8px 0 8px 24px; }
            li { margin: 4px 0; }

            strong { font-weight: 600; }
            em { font-style: italic; color: var(--text-muted); }

            blockquote {
                border-left: 4px solid var(--primary);
                padding: 10px 16px;
                margin: 12px 0;
                background: var(--primary-light);
                border-radius: 0 4px 4px 0;
            }

            code {
                font-family: 'JetBrains Mono', monospace;
                font-size: 9.5pt;
                background: #f1f5f9;
                padding: 2px 6px;
                border-radius: 3px;
            }

            pre {
                background: var(--code-bg);
                color: var(--code-text);
                padding: 16px 20px;
                border-radius: 8px;
                overflow-x: auto;
                margin: 12px 0;
                font-size: 9pt;
                line-height: 1.5;
            }

            pre code {
                background: none;
                padding: 0;
                color: inherit;
            }

            table {
                width: 100%;
                border-collapse: collapse;
                margin: 12px 0;
            }

            th, td {
                border: 1px solid var(--border);
                padding: 8px 12px;
                text-align: left;
            }

            th {
                background: var(--primary-light);
                font-weight: 600;
            }

            details {
                margin: 8px 0;
                padding: 8px 12px;
                background: #f8fafc;
                border-radius: 4px;
                border: 1px solid var(--border);
            }

            summary {
                cursor: pointer;
                font-weight: 500;
                color: var(--primary);
            }

            footer {
                margin-top: 40px;
                padding-top: 20px;
                border-top: 1px solid var(--border);
                text-align: center;
                font-size: 9pt;
                color: var(--text-muted);
            }

            @page {
                size: A4;
                margin: 2cm;
            }

            @media print {
                .document { padding: 0; }
                pre { page-break-inside: avoid; }
                h2, h3 { page-break-after: avoid; }
            }
        """
